name: WireMock Studio Build & Publish

on:
  push:
    branches-ignore:
      - 'abandoned-*'
  schedule:
    # Daily at 2AM
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  PROGRESS_NO_TRUNC: 1
  cache-name: docker-cache-1

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v2
        with:
          target: build-output
          outputs: build
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v2

      - uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: Unit Test Results
          files: |
            build/**/test-results/**/*.xml
